---
- name: Install Wireguard package
  tags: wireguard
  apt:
    name: "{{ packages }}"
  vars:
   packages:
     - wireguard
     - wireguard-tools

- name: Configure wireguard servers
  tags: wireguard
  template:
    src: wireguard.conf
    dest: "/etc/wireguard/{{ item.vpnName }}.conf"
    owner: root
    group: root
    mode: 0600
  loop: "{{ wireguardVPNs }}"
  when: item.vpnName in wireguardPeers 
  notify: restart wireguard-servers

- name: Configure systemd for wireguard
  tags: wireguard
  template:
    src: wg-quick@.service
    dest: "/etc/systemd/system/wg-quick@{{ item.vpnName }}.service"
    owner: root
    group: root
    mode: 0600
  loop: "{{ wireguardVPNs }}"
  when: item.vpnName in wireguardPeers 
  notify: restart wireguard-servers

- name: Enable wireguard services on systemd
  tags: wireguard
  systemd:
    name: "wg-quick@{{ item.vpnName }}"
    enabled: yes
  loop: "{{ wireguardVPNs }}"
  when: item.vpnName in wireguardPeers 
  notify: restart wireguard-servers

