---
- name: restart wireguard-servers
  systemd:
    name: "wg-quick@{{ item.vpnName }}"
    daemon_reload: yes
    state: restarted
  when: item.vpnName in wireguardPeers
  with_items:
   - "{{ wireguardVPNs }}"

